Update and rename .github/workflows/main.yml to .github/Deploy-Infra-App.yml

diff --git a/.github/Deploy-Infra-App.yml b/.github/Deploy-Infra-App.yml
--- a/.github/Deploy-Infra-App.yml
+++ b/.github/Deploy-Infra-App.yml
@@ -61,7 +61,7 @@ jobs:
       - name: Set up Docker
         uses: docker/setup-buildx-action@v2
 
-      - name: Build, Tag, and Push the Image to Amazon ECR
+     - name: Build, Tag, and Push the Image to Amazon ECR
         id: build-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
@@ -71,6 +71,12 @@ jobs:
           echo "ECR_REGISTRY: $ECR_REGISTRY"
           echo "ECR_REPOSITORY: $ECR_REPOSITORY"
           echo "IMAGE_TAG: $IMAGE_TAG"
+
+          if [ -z "$ECR_REGISTRY" ] || [ -z "$ECR_REPOSITORY" ] || [ -z "$IMAGE_TAG" ]; then
+            echo "One or more required environment variables are not set."
+            exit 1
+            
+          fi
           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
 
